//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elevate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elevate.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string HelpArg {
            get {
                return ResourceManager.GetString("HelpArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate {0}
        ///(c) 2007 - John Robbins - www.wintellect.com
        ///
        ///Execute a process on the command line with elevated rights on Vista
        ///
        ///Usage: Elevate [-?|-wait|-k] prog [args]
        ///   -?    - Shows this help  
        ///   -wait - Waits until prog terminates
        ///   -k    - Starts the the %comspec% environment variable value and 
        ///           executes prog in it (CMD.EXE, 4NT.EXE, etc.)
        ///   prog  - The program to execute
        ///   args  - Optional command line arguments to prog
        ///
        ///Note that because the way ShellExecute works, Elevate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Elevate argument: {0}.
        /// </summary>
        internal static string InvalidElevateArgFmt {
            get {
                return ResourceManager.GetString("InvalidElevateArgFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string KeepArg {
            get {
                return ResourceManager.GetString("KeepArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIT.
        /// </summary>
        internal static string WaitArg {
            get {
                return ResourceManager.GetString("WaitArg", resourceCulture);
            }
        }
    }
}
