// The file is auto generated by the Wintellect.Build.Tasks.GenerateAssemblyFileVersion task
#include "stdafx.h"
using namespace System;
using namespace System::Reflection;
[assembly:AssemblyFileVersion ( "4.0.10326.0" )]